/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { AcrossContractAddressesDto } from './acrossContractAddressesDto';

export interface AcrossDomainDto {
  chainId: number;
  contractAddresses: AcrossContractAddressesDto;
  createdAt: string;
  id: string;
  updatedAt: string;
}
