/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ConfirmationDto } from './confirmationDto';
import type { CcipTransactionType } from './ccipTransactionType';

export interface CcipBridgeDto {
  amount: string;
  createdAt: string;
  duration: number;
  from: string;
  fromSelector: string;
  id: string;
  receive?: ConfirmationDto;
  receiveAmount: string;
  send: ConfirmationDto;
  to: string;
  token: string;
  toSelector: string;
  type: CcipTransactionType;
  updatedAt: string;
}
