/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type CcipTransactionType = typeof CcipTransactionType[keyof typeof CcipTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CcipTransactionType = {
  'ccip-bridge': 'ccip-bridge',
} as const;
