/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { CcipBridgeMetadataDataDto } from './ccipBridgeMetadataDataDto';

export interface CcipBridgeMetadataDto {
  data: CcipBridgeMetadataDataDto;
  from: string;
  to: string;
  type: string;
}
