/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { HyperlaneContractAddressesDto } from './hyperlaneContractAddressesDto';

export interface HyperlaneMailboxDto {
  chainId: number;
  contractAddresses: HyperlaneContractAddressesDto;
  createdAt: string;
  domain: number;
  id: string;
}
