/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { LzContractAddressesV1Dto } from './lzContractAddressesV1Dto';
import type { LzContractAddressesV2Dto } from './lzContractAddressesV2Dto';

export type LzDomainDtoContractAddresses = LzContractAddressesV1Dto | LzContractAddressesV2Dto;
