/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { FiatOnrampFee } from './fiatOnrampFee';
import type { TokenOnrampFee } from './tokenOnrampFee';

export interface OnrampFee {
  fiat?: FiatOnrampFee;
  name: string;
  token?: TokenOnrampFee;
}
