/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type OnrampQuoteErrorType = typeof OnrampQuoteErrorType[keyof typeof OnrampQuoteErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnrampQuoteErrorType = {
  GenericError: 'GenericError',
  AmountTooSmall: 'AmountTooSmall',
  AmountTooLarge: 'AmountTooLarge',
} as const;
