/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OnrampQuote } from './onrampQuote';
import type { OnrampQuoteGenericErrorDto } from './onrampQuoteGenericErrorDto';
import type { OnrampQuoteAmountTooSmallErrorDto } from './onrampQuoteAmountTooSmallErrorDto';
import type { OnrampQuoteAmountTooLargeErrorDto } from './onrampQuoteAmountTooLargeErrorDto';

export type OnrampQuoteResponseDtoResult = OnrampQuote | OnrampQuoteGenericErrorDto | OnrampQuoteAmountTooSmallErrorDto | OnrampQuoteAmountTooLargeErrorDto;
