/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OnrampFee } from './onrampFee';
import type { OnrampQuoteMoonPay } from './onrampQuoteMoonPay';
import type { OnrampQuoteProvider } from './onrampQuoteProvider';

export interface OnrampQuote {
  fees: OnrampFee[];
  fiatAmount: string;
  fiatCurrency: string;
  moonPay: OnrampQuoteMoonPay;
  provider: OnrampQuoteProvider;
  tokenAmount: string;
}
