/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OnrampQuoteErrorType } from './onrampQuoteErrorType';

export interface OnrampQuoteGenericErrorDto {
  error: string;
  type: OnrampQuoteErrorType;
}
