/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OnrampFeeFiat } from './onrampFeeFiat';
import type { OnrampFeeToken } from './onrampFeeToken';

export interface OnrampFee {
  fiat: OnrampFeeFiat;
  name: string;
  token: OnrampFeeToken;
}
