/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type OnrampControllerGetQuotesParams = {
tokenAddress: string;
chainId: string;
fiatCurrency: string;
fiatAmount?: string;
tokenAmount?: string;
};
