/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { CcipRouteRequestDto } from './ccipRouteRequestDto';
import type { HyperlaneRouteRequestDto } from './hyperlaneRouteRequestDto';
import type { LzRouteRequestDto } from './lzRouteRequestDto';

export interface RouteRequestDto {
  amount: string;
  ccip?: CcipRouteRequestDto;
  forceViaL1: boolean;
  fromChainId: string;
  fromTokenAddress: string;
  graffiti: string;
  host: string;
  hyperlane?: HyperlaneRouteRequestDto;
  hyperlaneCustomRoutesId?: string;
  hyperlaneFromTokenRouterAddress?: string;
  hyperlaneToTokenRouterAddress?: string;
  lz?: LzRouteRequestDto;
  lzAdapter?: string;
  opBridgedUsdcAdapter?: string;
  recipient: string;
  sender: string;
  skyBridge?: string;
  toChainId: string;
  toTokenAddress: string;
}
